//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoughMinder___Client.DoughMinderServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insumo", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Insumo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CantidadKiloLitroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioKiloLitroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaFotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CantidadKiloLitro {
            get {
                return this.CantidadKiloLitroField;
            }
            set {
                if ((this.CantidadKiloLitroField.Equals(value) != true)) {
                    this.CantidadKiloLitroField = value;
                    this.RaisePropertyChanged("CantidadKiloLitro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInsumo {
            get {
                return this.IdInsumoField;
            }
            set {
                if ((this.IdInsumoField.Equals(value) != true)) {
                    this.IdInsumoField = value;
                    this.RaisePropertyChanged("IdInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoReceta {
            get {
                return this.InsumoRecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.InsumoRecetaField, value) != true)) {
                    this.InsumoRecetaField = value;
                    this.RaisePropertyChanged("InsumoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrecioKiloLitro {
            get {
                return this.PrecioKiloLitroField;
            }
            set {
                if ((this.PrecioKiloLitroField.Equals(value) != true)) {
                    this.PrecioKiloLitroField = value;
                    this.RaisePropertyChanged("PrecioKiloLitro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFoto {
            get {
                return this.RutaFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaFotoField, value) != true)) {
                    this.RutaFotoField = value;
                    this.RaisePropertyChanged("RutaFoto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsumoReceta", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class InsumoReceta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInsumoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Insumo InsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Receta RecetaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdInsumo {
            get {
                return this.IdInsumoField;
            }
            set {
                if ((this.IdInsumoField.Equals(value) != true)) {
                    this.IdInsumoField = value;
                    this.RaisePropertyChanged("IdInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInsumoReceta {
            get {
                return this.IdInsumoRecetaField;
            }
            set {
                if ((this.IdInsumoRecetaField.Equals(value) != true)) {
                    this.IdInsumoRecetaField = value;
                    this.RaisePropertyChanged("IdInsumoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdReceta {
            get {
                return this.IdRecetaField;
            }
            set {
                if ((this.IdRecetaField.Equals(value) != true)) {
                    this.IdRecetaField = value;
                    this.RaisePropertyChanged("IdReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Insumo Insumo {
            get {
                return this.InsumoField;
            }
            set {
                if ((object.ReferenceEquals(this.InsumoField, value) != true)) {
                    this.InsumoField = value;
                    this.RaisePropertyChanged("Insumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Receta Receta {
            get {
                return this.RecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.RecetaField, value) != true)) {
                    this.RecetaField = value;
                    this.RaisePropertyChanged("Receta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receta", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Receta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Producto[] ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReceta {
            get {
                return this.IdRecetaField;
            }
            set {
                if ((this.IdRecetaField.Equals(value) != true)) {
                    this.IdRecetaField = value;
                    this.RaisePropertyChanged("IdReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoReceta {
            get {
                return this.InsumoRecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.InsumoRecetaField, value) != true)) {
                    this.InsumoRecetaField = value;
                    this.RaisePropertyChanged("InsumoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Producto[] Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Receta RecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestriccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProductoField, value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdReceta {
            get {
                return this.IdRecetaField;
            }
            set {
                if ((this.IdRecetaField.Equals(value) != true)) {
                    this.IdRecetaField = value;
                    this.RaisePropertyChanged("IdReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProducto {
            get {
                return this.PedidoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoProductoField, value) != true)) {
                    this.PedidoProductoField = value;
                    this.RaisePropertyChanged("PedidoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Receta Receta {
            get {
                return this.RecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.RecetaField, value) != true)) {
                    this.RecetaField = value;
                    this.RaisePropertyChanged("Receta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restricciones {
            get {
                return this.RestriccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionesField, value) != true)) {
                    this.RestriccionesField = value;
                    this.RaisePropertyChanged("Restricciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFoto {
            get {
                return this.RutaFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaFotoField, value) != true)) {
                    this.RutaFotoField = value;
                    this.RaisePropertyChanged("RutaFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProducto {
            get {
                return this.SolicitudProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudProductoField, value) != true)) {
                    this.SolicitudProductoField = value;
                    this.RaisePropertyChanged("SolicitudProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoProducto", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class PedidoProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Pedido PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Producto ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveProducto {
            get {
                return this.ClaveProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveProductoField, value) != true)) {
                    this.ClaveProductoField = value;
                    this.RaisePropertyChanged("ClaveProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedidoProducto {
            get {
                return this.IdPedidoProductoField;
            }
            set {
                if ((this.IdPedidoProductoField.Equals(value) != true)) {
                    this.IdPedidoProductoField = value;
                    this.RaisePropertyChanged("IdPedidoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Pedido Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudProducto", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class SolicitudProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSolicitudProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Producto ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Solicitud SolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveProducto {
            get {
                return this.ClaveProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveProductoField, value) != true)) {
                    this.ClaveProductoField = value;
                    this.RaisePropertyChanged("ClaveProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdSolicitud {
            get {
                return this.IdSolicitudField;
            }
            set {
                if ((this.IdSolicitudField.Equals(value) != true)) {
                    this.IdSolicitudField = value;
                    this.RaisePropertyChanged("IdSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSolicitudProducto {
            get {
                return this.IdSolicitudProductoField;
            }
            set {
                if ((this.IdSolicitudProductoField.Equals(value) != true)) {
                    this.IdSolicitudProductoField = value;
                    this.RaisePropertyChanged("IdSolicitudProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Solicitud Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CostoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.EstadoPedido EstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdEstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEntregaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CostoTotal {
            get {
                return this.CostoTotalField;
            }
            set {
                if ((this.CostoTotalField.Equals(value) != true)) {
                    this.CostoTotalField = value;
                    this.RaisePropertyChanged("CostoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.EstadoPedido EstadoPedido {
            get {
                return this.EstadoPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoPedidoField, value) != true)) {
                    this.EstadoPedidoField = value;
                    this.RaisePropertyChanged("EstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdEstadoPedido {
            get {
                return this.IdEstadoPedidoField;
            }
            set {
                if ((this.IdEstadoPedidoField.Equals(value) != true)) {
                    this.IdEstadoPedidoField = value;
                    this.RaisePropertyChanged("IdEstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProducto {
            get {
                return this.PedidoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoProductoField, value) != true)) {
                    this.PedidoProductoField = value;
                    this.RaisePropertyChanged("PedidoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEntrega {
            get {
                return this.TipoEntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEntregaField, value) != true)) {
                    this.TipoEntregaField = value;
                    this.RaisePropertyChanged("TipoEntrega");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPedido", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class EstadoPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoPedido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Pedido[] PedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoPedido1 {
            get {
                return this.EstadoPedido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoPedido1Field, value) != true)) {
                    this.EstadoPedido1Field = value;
                    this.RaisePropertyChanged("EstadoPedido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoPedido {
            get {
                return this.IdEstadoPedidoField;
            }
            set {
                if ((this.IdEstadoPedidoField.Equals(value) != true)) {
                    this.IdEstadoPedidoField = value;
                    this.RaisePropertyChanged("IdEstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Pedido[] Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CostoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Proveedor ProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CostoTotal {
            get {
                return this.CostoTotalField;
            }
            set {
                if ((this.CostoTotalField.Equals(value) != true)) {
                    this.CostoTotalField = value;
                    this.RaisePropertyChanged("CostoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdProveedor {
            get {
                return this.IdProveedorField;
            }
            set {
                if ((this.IdProveedorField.Equals(value) != true)) {
                    this.IdProveedorField = value;
                    this.RaisePropertyChanged("IdProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSolicitud {
            get {
                return this.IdSolicitudField;
            }
            set {
                if ((this.IdSolicitudField.Equals(value) != true)) {
                    this.IdSolicitudField = value;
                    this.RaisePropertyChanged("IdSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Proveedor Proveedor {
            get {
                return this.ProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true)) {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProducto {
            get {
                return this.SolicitudProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudProductoField, value) != true)) {
                    this.SolicitudProductoField = value;
                    this.RaisePropertyChanged("SolicitudProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Solicitud[] SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProveedor {
            get {
                return this.IdProveedorField;
            }
            set {
                if ((this.IdProveedorField.Equals(value) != true)) {
                    this.IdProveedorField = value;
                    this.RaisePropertyChanged("IdProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Solicitud[] Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CostoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMovimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CostoTotal {
            get {
                return this.CostoTotalField;
            }
            set {
                if ((this.CostoTotalField.Equals(value) != true)) {
                    this.CostoTotalField = value;
                    this.RaisePropertyChanged("CostoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMovimiento {
            get {
                return this.IdMovimientoField;
            }
            set {
                if ((this.IdMovimientoField.Equals(value) != true)) {
                    this.IdMovimientoField = value;
                    this.RaisePropertyChanged("IdMovimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdPuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Puesto PuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPuesto {
            get {
                return this.IdPuestoField;
            }
            set {
                if ((this.IdPuestoField.Equals(value) != true)) {
                    this.IdPuestoField = value;
                    this.RaisePropertyChanged("IdPuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno {
            get {
                return this.MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternoField, value) != true)) {
                    this.MaternoField = value;
                    this.RaisePropertyChanged("Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno {
            get {
                return this.PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternoField, value) != true)) {
                    this.PaternoField = value;
                    this.RaisePropertyChanged("Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Puesto Puesto {
            get {
                return this.PuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.PuestoField, value) != true)) {
                    this.PuestoField = value;
                    this.RaisePropertyChanged("Puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Puesto", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Puesto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Empleado[] EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Puesto1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Empleado[] Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPuesto {
            get {
                return this.IdPuestoField;
            }
            set {
                if ((this.IdPuestoField.Equals(value) != true)) {
                    this.IdPuestoField = value;
                    this.RaisePropertyChanged("IdPuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puesto1 {
            get {
                return this.Puesto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Puesto1Field, value) != true)) {
                    this.Puesto1Field = value;
                    this.RaisePropertyChanged("Puesto1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoughMinderServicio.IInsumo")]
    public interface IInsumo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/GuardarInsumo", ReplyAction="http://tempuri.org/IInsumo/GuardarInsumoResponse")]
        int GuardarInsumo(DoughMinder___Client.DoughMinderServicio.Insumo insumo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/GuardarInsumo", ReplyAction="http://tempuri.org/IInsumo/GuardarInsumoResponse")]
        System.Threading.Tasks.Task<int> GuardarInsumoAsync(DoughMinder___Client.DoughMinderServicio.Insumo insumo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/RecuperarInsumos", ReplyAction="http://tempuri.org/IInsumo/RecuperarInsumosResponse")]
        System.Collections.Generic.Dictionary<int, string> RecuperarInsumos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/RecuperarInsumos", ReplyAction="http://tempuri.org/IInsumo/RecuperarInsumosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> RecuperarInsumosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/RecuperarTodosInsumos", ReplyAction="http://tempuri.org/IInsumo/RecuperarTodosInsumosResponse")]
        DoughMinder___Client.DoughMinderServicio.Insumo[] RecuperarTodosInsumos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/RecuperarTodosInsumos", ReplyAction="http://tempuri.org/IInsumo/RecuperarTodosInsumosResponse")]
        System.Threading.Tasks.Task<DoughMinder___Client.DoughMinderServicio.Insumo[]> RecuperarTodosInsumosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsumoChannel : DoughMinder___Client.DoughMinderServicio.IInsumo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsumoClient : System.ServiceModel.ClientBase<DoughMinder___Client.DoughMinderServicio.IInsumo>, DoughMinder___Client.DoughMinderServicio.IInsumo {
        
        public InsumoClient() {
        }
        
        public InsumoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsumoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GuardarInsumo(DoughMinder___Client.DoughMinderServicio.Insumo insumo) {
            return base.Channel.GuardarInsumo(insumo);
        }
        
        public System.Threading.Tasks.Task<int> GuardarInsumoAsync(DoughMinder___Client.DoughMinderServicio.Insumo insumo) {
            return base.Channel.GuardarInsumoAsync(insumo);
        }
        
        public System.Collections.Generic.Dictionary<int, string> RecuperarInsumos() {
            return base.Channel.RecuperarInsumos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> RecuperarInsumosAsync() {
            return base.Channel.RecuperarInsumosAsync();
        }
        
        public DoughMinder___Client.DoughMinderServicio.Insumo[] RecuperarTodosInsumos() {
            return base.Channel.RecuperarTodosInsumos();
        }
        
        public System.Threading.Tasks.Task<DoughMinder___Client.DoughMinderServicio.Insumo[]> RecuperarTodosInsumosAsync() {
            return base.Channel.RecuperarTodosInsumosAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoughMinderServicio.IReceta")]
    public interface IReceta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceta/GuardarReceta", ReplyAction="http://tempuri.org/IReceta/GuardarRecetaResponse")]
        int GuardarReceta(DoughMinder___Client.DoughMinderServicio.Receta receta, System.Collections.Generic.Dictionary<int, float> listaInsumos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceta/GuardarReceta", ReplyAction="http://tempuri.org/IReceta/GuardarRecetaResponse")]
        System.Threading.Tasks.Task<int> GuardarRecetaAsync(DoughMinder___Client.DoughMinderServicio.Receta receta, System.Collections.Generic.Dictionary<int, float> listaInsumos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceta/RecuperarRecetas", ReplyAction="http://tempuri.org/IReceta/RecuperarRecetasResponse")]
        System.Collections.Generic.Dictionary<int, string> RecuperarRecetas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceta/RecuperarRecetas", ReplyAction="http://tempuri.org/IReceta/RecuperarRecetasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> RecuperarRecetasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecetaChannel : DoughMinder___Client.DoughMinderServicio.IReceta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecetaClient : System.ServiceModel.ClientBase<DoughMinder___Client.DoughMinderServicio.IReceta>, DoughMinder___Client.DoughMinderServicio.IReceta {
        
        public RecetaClient() {
        }
        
        public RecetaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecetaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecetaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecetaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GuardarReceta(DoughMinder___Client.DoughMinderServicio.Receta receta, System.Collections.Generic.Dictionary<int, float> listaInsumos) {
            return base.Channel.GuardarReceta(receta, listaInsumos);
        }
        
        public System.Threading.Tasks.Task<int> GuardarRecetaAsync(DoughMinder___Client.DoughMinderServicio.Receta receta, System.Collections.Generic.Dictionary<int, float> listaInsumos) {
            return base.Channel.GuardarRecetaAsync(receta, listaInsumos);
        }
        
        public System.Collections.Generic.Dictionary<int, string> RecuperarRecetas() {
            return base.Channel.RecuperarRecetas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> RecuperarRecetasAsync() {
            return base.Channel.RecuperarRecetasAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoughMinderServicio.IMovimiento")]
    public interface IMovimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento/RegistrarMovimiento", ReplyAction="http://tempuri.org/IMovimiento/RegistrarMovimientoResponse")]
        int RegistrarMovimiento(DoughMinder___Client.DoughMinderServicio.Movimiento movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento/RegistrarMovimiento", ReplyAction="http://tempuri.org/IMovimiento/RegistrarMovimientoResponse")]
        System.Threading.Tasks.Task<int> RegistrarMovimientoAsync(DoughMinder___Client.DoughMinderServicio.Movimiento movimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovimientoChannel : DoughMinder___Client.DoughMinderServicio.IMovimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovimientoClient : System.ServiceModel.ClientBase<DoughMinder___Client.DoughMinderServicio.IMovimiento>, DoughMinder___Client.DoughMinderServicio.IMovimiento {
        
        public MovimientoClient() {
        }
        
        public MovimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarMovimiento(DoughMinder___Client.DoughMinderServicio.Movimiento movimiento) {
            return base.Channel.RegistrarMovimiento(movimiento);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarMovimientoAsync(DoughMinder___Client.DoughMinderServicio.Movimiento movimiento) {
            return base.Channel.RegistrarMovimientoAsync(movimiento);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoughMinderServicio.IProducto")]
    public interface IProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/GuardarProducto", ReplyAction="http://tempuri.org/IProducto/GuardarProductoResponse")]
        int GuardarProducto(DoughMinder___Client.DoughMinderServicio.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/GuardarProducto", ReplyAction="http://tempuri.org/IProducto/GuardarProductoResponse")]
        System.Threading.Tasks.Task<int> GuardarProductoAsync(DoughMinder___Client.DoughMinderServicio.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/RecuperarProductosSinReceta", ReplyAction="http://tempuri.org/IProducto/RecuperarProductosSinRecetaResponse")]
        DoughMinder___Client.DoughMinderServicio.Producto[] RecuperarProductosSinReceta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/RecuperarProductosSinReceta", ReplyAction="http://tempuri.org/IProducto/RecuperarProductosSinRecetaResponse")]
        System.Threading.Tasks.Task<DoughMinder___Client.DoughMinderServicio.Producto[]> RecuperarProductosSinRecetaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoChannel : DoughMinder___Client.DoughMinderServicio.IProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoClient : System.ServiceModel.ClientBase<DoughMinder___Client.DoughMinderServicio.IProducto>, DoughMinder___Client.DoughMinderServicio.IProducto {
        
        public ProductoClient() {
        }
        
        public ProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GuardarProducto(DoughMinder___Client.DoughMinderServicio.Producto producto) {
            return base.Channel.GuardarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<int> GuardarProductoAsync(DoughMinder___Client.DoughMinderServicio.Producto producto) {
            return base.Channel.GuardarProductoAsync(producto);
        }
        
        public DoughMinder___Client.DoughMinderServicio.Producto[] RecuperarProductosSinReceta() {
            return base.Channel.RecuperarProductosSinReceta();
        }
        
        public System.Threading.Tasks.Task<DoughMinder___Client.DoughMinderServicio.Producto[]> RecuperarProductosSinRecetaAsync() {
            return base.Channel.RecuperarProductosSinRecetaAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoughMinderServicio.IEmpleado")]
    public interface IEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/GuardarEmpleado", ReplyAction="http://tempuri.org/IEmpleado/GuardarEmpleadoResponse")]
        int GuardarEmpleado(DoughMinder___Client.DoughMinderServicio.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/GuardarEmpleado", ReplyAction="http://tempuri.org/IEmpleado/GuardarEmpleadoResponse")]
        System.Threading.Tasks.Task<int> GuardarEmpleadoAsync(DoughMinder___Client.DoughMinderServicio.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/RecuperarEmpleados", ReplyAction="http://tempuri.org/IEmpleado/RecuperarEmpleadosResponse")]
        System.Collections.Generic.Dictionary<string, string> RecuperarEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/RecuperarEmpleados", ReplyAction="http://tempuri.org/IEmpleado/RecuperarEmpleadosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> RecuperarEmpleadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoChannel : DoughMinder___Client.DoughMinderServicio.IEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoClient : System.ServiceModel.ClientBase<DoughMinder___Client.DoughMinderServicio.IEmpleado>, DoughMinder___Client.DoughMinderServicio.IEmpleado {
        
        public EmpleadoClient() {
        }
        
        public EmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GuardarEmpleado(DoughMinder___Client.DoughMinderServicio.Empleado empleado) {
            return base.Channel.GuardarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<int> GuardarEmpleadoAsync(DoughMinder___Client.DoughMinderServicio.Empleado empleado) {
            return base.Channel.GuardarEmpleadoAsync(empleado);
        }
        
        public System.Collections.Generic.Dictionary<string, string> RecuperarEmpleados() {
            return base.Channel.RecuperarEmpleados();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> RecuperarEmpleadosAsync() {
            return base.Channel.RecuperarEmpleadosAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoughMinderServicio.IProveedor")]
    public interface IProveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/GuardarProveedor", ReplyAction="http://tempuri.org/IProveedor/GuardarProveedorResponse")]
        int GuardarProveedor(DoughMinder___Client.DoughMinderServicio.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/GuardarProveedor", ReplyAction="http://tempuri.org/IProveedor/GuardarProveedorResponse")]
        System.Threading.Tasks.Task<int> GuardarProveedorAsync(DoughMinder___Client.DoughMinderServicio.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/RecuperarProveedores", ReplyAction="http://tempuri.org/IProveedor/RecuperarProveedoresResponse")]
        DoughMinder___Client.DoughMinderServicio.Proveedor[] RecuperarProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/RecuperarProveedores", ReplyAction="http://tempuri.org/IProveedor/RecuperarProveedoresResponse")]
        System.Threading.Tasks.Task<DoughMinder___Client.DoughMinderServicio.Proveedor[]> RecuperarProveedoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProveedorChannel : DoughMinder___Client.DoughMinderServicio.IProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedorClient : System.ServiceModel.ClientBase<DoughMinder___Client.DoughMinderServicio.IProveedor>, DoughMinder___Client.DoughMinderServicio.IProveedor {
        
        public ProveedorClient() {
        }
        
        public ProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GuardarProveedor(DoughMinder___Client.DoughMinderServicio.Proveedor proveedor) {
            return base.Channel.GuardarProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task<int> GuardarProveedorAsync(DoughMinder___Client.DoughMinderServicio.Proveedor proveedor) {
            return base.Channel.GuardarProveedorAsync(proveedor);
        }
        
        public DoughMinder___Client.DoughMinderServicio.Proveedor[] RecuperarProveedores() {
            return base.Channel.RecuperarProveedores();
        }
        
        public System.Threading.Tasks.Task<DoughMinder___Client.DoughMinderServicio.Proveedor[]> RecuperarProveedoresAsync() {
            return base.Channel.RecuperarProveedoresAsync();
        }
    }
}
