//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoughMinder___Client.DoughMinderServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insumo", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Insumo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CantidadKiloLitroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioKiloLitroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaFotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CantidadKiloLitro {
            get {
                return this.CantidadKiloLitroField;
            }
            set {
                if ((this.CantidadKiloLitroField.Equals(value) != true)) {
                    this.CantidadKiloLitroField = value;
                    this.RaisePropertyChanged("CantidadKiloLitro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInsumo {
            get {
                return this.IdInsumoField;
            }
            set {
                if ((this.IdInsumoField.Equals(value) != true)) {
                    this.IdInsumoField = value;
                    this.RaisePropertyChanged("IdInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoReceta {
            get {
                return this.InsumoRecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.InsumoRecetaField, value) != true)) {
                    this.InsumoRecetaField = value;
                    this.RaisePropertyChanged("InsumoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrecioKiloLitro {
            get {
                return this.PrecioKiloLitroField;
            }
            set {
                if ((this.PrecioKiloLitroField.Equals(value) != true)) {
                    this.PrecioKiloLitroField = value;
                    this.RaisePropertyChanged("PrecioKiloLitro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFoto {
            get {
                return this.RutaFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaFotoField, value) != true)) {
                    this.RutaFotoField = value;
                    this.RaisePropertyChanged("RutaFoto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsumoReceta", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class InsumoReceta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInsumoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Insumo InsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Receta RecetaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdInsumo {
            get {
                return this.IdInsumoField;
            }
            set {
                if ((this.IdInsumoField.Equals(value) != true)) {
                    this.IdInsumoField = value;
                    this.RaisePropertyChanged("IdInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInsumoReceta {
            get {
                return this.IdInsumoRecetaField;
            }
            set {
                if ((this.IdInsumoRecetaField.Equals(value) != true)) {
                    this.IdInsumoRecetaField = value;
                    this.RaisePropertyChanged("IdInsumoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdReceta {
            get {
                return this.IdRecetaField;
            }
            set {
                if ((this.IdRecetaField.Equals(value) != true)) {
                    this.IdRecetaField = value;
                    this.RaisePropertyChanged("IdReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Insumo Insumo {
            get {
                return this.InsumoField;
            }
            set {
                if ((object.ReferenceEquals(this.InsumoField, value) != true)) {
                    this.InsumoField = value;
                    this.RaisePropertyChanged("Insumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Receta Receta {
            get {
                return this.RecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.RecetaField, value) != true)) {
                    this.RecetaField = value;
                    this.RaisePropertyChanged("Receta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receta", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Receta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Producto[] ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReceta {
            get {
                return this.IdRecetaField;
            }
            set {
                if ((this.IdRecetaField.Equals(value) != true)) {
                    this.IdRecetaField = value;
                    this.RaisePropertyChanged("IdReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.InsumoReceta[] InsumoReceta {
            get {
                return this.InsumoRecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.InsumoRecetaField, value) != true)) {
                    this.InsumoRecetaField = value;
                    this.RaisePropertyChanged("InsumoReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Producto[] Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdRecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Receta RecetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestriccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProductoField, value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdReceta {
            get {
                return this.IdRecetaField;
            }
            set {
                if ((this.IdRecetaField.Equals(value) != true)) {
                    this.IdRecetaField = value;
                    this.RaisePropertyChanged("IdReceta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProducto {
            get {
                return this.PedidoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoProductoField, value) != true)) {
                    this.PedidoProductoField = value;
                    this.RaisePropertyChanged("PedidoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Receta Receta {
            get {
                return this.RecetaField;
            }
            set {
                if ((object.ReferenceEquals(this.RecetaField, value) != true)) {
                    this.RecetaField = value;
                    this.RaisePropertyChanged("Receta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restricciones {
            get {
                return this.RestriccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.RestriccionesField, value) != true)) {
                    this.RestriccionesField = value;
                    this.RaisePropertyChanged("Restricciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFoto {
            get {
                return this.RutaFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaFotoField, value) != true)) {
                    this.RutaFotoField = value;
                    this.RaisePropertyChanged("RutaFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProducto {
            get {
                return this.SolicitudProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudProductoField, value) != true)) {
                    this.SolicitudProductoField = value;
                    this.RaisePropertyChanged("SolicitudProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoProducto", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class PedidoProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Pedido PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Producto ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveProducto {
            get {
                return this.ClaveProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveProductoField, value) != true)) {
                    this.ClaveProductoField = value;
                    this.RaisePropertyChanged("ClaveProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedidoProducto {
            get {
                return this.IdPedidoProductoField;
            }
            set {
                if ((this.IdPedidoProductoField.Equals(value) != true)) {
                    this.IdPedidoProductoField = value;
                    this.RaisePropertyChanged("IdPedidoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Pedido Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudProducto", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class SolicitudProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSolicitudProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Producto ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Solicitud SolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveProducto {
            get {
                return this.ClaveProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveProductoField, value) != true)) {
                    this.ClaveProductoField = value;
                    this.RaisePropertyChanged("ClaveProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdSolicitud {
            get {
                return this.IdSolicitudField;
            }
            set {
                if ((this.IdSolicitudField.Equals(value) != true)) {
                    this.IdSolicitudField = value;
                    this.RaisePropertyChanged("IdSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSolicitudProducto {
            get {
                return this.IdSolicitudProductoField;
            }
            set {
                if ((this.IdSolicitudProductoField.Equals(value) != true)) {
                    this.IdSolicitudProductoField = value;
                    this.RaisePropertyChanged("IdSolicitudProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Solicitud Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CostoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.EstadoPedido EstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdEstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEntregaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CostoTotal {
            get {
                return this.CostoTotalField;
            }
            set {
                if ((this.CostoTotalField.Equals(value) != true)) {
                    this.CostoTotalField = value;
                    this.RaisePropertyChanged("CostoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.EstadoPedido EstadoPedido {
            get {
                return this.EstadoPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoPedidoField, value) != true)) {
                    this.EstadoPedidoField = value;
                    this.RaisePropertyChanged("EstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdEstadoPedido {
            get {
                return this.IdEstadoPedidoField;
            }
            set {
                if ((this.IdEstadoPedidoField.Equals(value) != true)) {
                    this.IdEstadoPedidoField = value;
                    this.RaisePropertyChanged("IdEstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.PedidoProducto[] PedidoProducto {
            get {
                return this.PedidoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoProductoField, value) != true)) {
                    this.PedidoProductoField = value;
                    this.RaisePropertyChanged("PedidoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEntrega {
            get {
                return this.TipoEntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEntregaField, value) != true)) {
                    this.TipoEntregaField = value;
                    this.RaisePropertyChanged("TipoEntrega");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPedido", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class EstadoPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoPedido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Pedido[] PedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoPedido1 {
            get {
                return this.EstadoPedido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoPedido1Field, value) != true)) {
                    this.EstadoPedido1Field = value;
                    this.RaisePropertyChanged("EstadoPedido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoPedido {
            get {
                return this.IdEstadoPedidoField;
            }
            set {
                if ((this.IdEstadoPedidoField.Equals(value) != true)) {
                    this.IdEstadoPedidoField = value;
                    this.RaisePropertyChanged("IdEstadoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Pedido[] Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CostoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Proveedor ProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CostoTotal {
            get {
                return this.CostoTotalField;
            }
            set {
                if ((this.CostoTotalField.Equals(value) != true)) {
                    this.CostoTotalField = value;
                    this.RaisePropertyChanged("CostoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdProveedor {
            get {
                return this.IdProveedorField;
            }
            set {
                if ((this.IdProveedorField.Equals(value) != true)) {
                    this.IdProveedorField = value;
                    this.RaisePropertyChanged("IdProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSolicitud {
            get {
                return this.IdSolicitudField;
            }
            set {
                if ((this.IdSolicitudField.Equals(value) != true)) {
                    this.IdSolicitudField = value;
                    this.RaisePropertyChanged("IdSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Proveedor Proveedor {
            get {
                return this.ProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true)) {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.SolicitudProducto[] SolicitudProducto {
            get {
                return this.SolicitudProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudProductoField, value) != true)) {
                    this.SolicitudProductoField = value;
                    this.RaisePropertyChanged("SolicitudProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/Clases")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DoughMinder___Client.DoughMinderServicio.Solicitud[] SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProveedor {
            get {
                return this.IdProveedorField;
            }
            set {
                if ((this.IdProveedorField.Equals(value) != true)) {
                    this.IdProveedorField = value;
                    this.RaisePropertyChanged("IdProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DoughMinder___Client.DoughMinderServicio.Solicitud[] Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoughMinderServicio.IInsumo")]
    public interface IInsumo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/GuardarInsumo", ReplyAction="http://tempuri.org/IInsumo/GuardarInsumoResponse")]
        int GuardarInsumo(DoughMinder___Client.DoughMinderServicio.Insumo insumo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumo/GuardarInsumo", ReplyAction="http://tempuri.org/IInsumo/GuardarInsumoResponse")]
        System.Threading.Tasks.Task<int> GuardarInsumoAsync(DoughMinder___Client.DoughMinderServicio.Insumo insumo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsumoChannel : DoughMinder___Client.DoughMinderServicio.IInsumo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsumoClient : System.ServiceModel.ClientBase<DoughMinder___Client.DoughMinderServicio.IInsumo>, DoughMinder___Client.DoughMinderServicio.IInsumo {
        
        public InsumoClient() {
        }
        
        public InsumoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsumoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GuardarInsumo(DoughMinder___Client.DoughMinderServicio.Insumo insumo) {
            return base.Channel.GuardarInsumo(insumo);
        }
        
        public System.Threading.Tasks.Task<int> GuardarInsumoAsync(DoughMinder___Client.DoughMinderServicio.Insumo insumo) {
            return base.Channel.GuardarInsumoAsync(insumo);
        }
    }
}
